version: "2"

services:
  fbtools:
    build: .
#    image: "docker.io/acoby/fbtools:latest"
    restart: "unless-stopped"
    depends_on:
      - "database"
    ports:
      - "1291:80"
    volumes:
      - "./app/var/www:/var/www"
      - "./data/log:/var/log"
    env_file:
      - ".env"

  database:
    image: "docker.io/mariadb:latest"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: "unless-stopped"
    volumes:
      - "./data/db:/var/lib/mysql"
    env_file:
      - ".env"
